# Generated by Django 4.0.5 on 2022-06-06 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ducks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snack',
            new_name='Duck',
        ),
    ]
